# Generated by Django 3.2.4 on 2021-06-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('store', 'product')},
        ),
    ]
